services:
  oracle-xe:
    image: gvenzl/oracle-xe
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=admin123
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./db/init-iess-user.sql:/docker-entrypoint-initdb.d/init-iess-user.sql
    networks:
      - iess-net

    healthcheck:
      test: [ "CMD-SHELL", "sqlplus -L sys/admin123@XEPDB1 AS SYSDBA <<< 'select 1 from dual;'" ]
      interval: 10s
      timeout: 5s
      retries: 20  # Aumenta los reintentos para dar más tiempo
      start_period: 120s # Espera hasta 2 minutos antes de empezar a chequear

  quarkus-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quarkus-iess-app
    ports:
      - "8085:8085"
    networks:
          - iess-net

    depends_on:
      oracle-xe:
        condition: service_healthy # Espera a que Oracle esté 'healthy'

networks:
  iess-net:
    driver: bridge



