-- ==========================================================
-- Script de inicialización para Oracle XE - Proyecto IESS
-- Crea el usuario IESS_USER, otorga privilegios y genera tablas
-- ==========================================================

-- 1️⃣ Crear usuario (si no existe)
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER IESS_USER IDENTIFIED BY IESS123 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -01920 THEN
      NULL; -- Usuario ya existe, continuar
    ELSE
      RAISE;
    END IF;
END;
/

-- 2️⃣ Otorgar privilegios necesarios
GRANT CONNECT, RESOURCE TO IESS_USER;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE TRIGGER TO IESS_USER;
ALTER USER IESS_USER QUOTA UNLIMITED ON USERS;

-- 3️⃣ Conectarse al esquema
ALTER SESSION SET CURRENT_SCHEMA = IESS_USER;

-- 4️⃣ Crear tablas del sistema
-- ==========================================================
-- Tabla CLIENTE
-- ==========================================================
CREATE TABLE CLIENTE (
    CLIENTE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    GENERO VARCHAR2(20),
    EDAD NUMBER(3),
    IDENTIFICACION VARCHAR2(20) UNIQUE NOT NULL,
    DIRECCION VARCHAR2(150),
    TELEFONO VARCHAR2(20),
    CONTRASENA VARCHAR2(100),
    ESTADO NUMBER(1)
);

-- ==========================================================
-- Tabla CUENTA
-- ==========================================================
CREATE TABLE CUENTA (
    CUENTA_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CLIENTE_ID NUMBER NOT NULL,
    NUMERO_CUENTA VARCHAR2(20) UNIQUE NOT NULL,
    SALDO NUMBER(10,2) DEFAULT 0,
    CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE_ID)
        REFERENCES CLIENTE (CLIENTE_ID)
        ON DELETE CASCADE
);

-- ==========================================================
-- Tabla MOVIMIENTO
-- ==========================================================
CREATE TABLE MOVIMIENTO (
    MOVIMIENTO_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CUENTA_ID NUMBER NOT NULL,
    FECHA DATE DEFAULT SYSDATE,
    TIPO_MOVIMIENTO VARCHAR2(20) CHECK (TIPO_MOVIMIENTO IN ('CREDITO', 'DEBITO')),
    VALOR NUMBER(10,2) NOT NULL,
    SALDO_DISPONIBLE NUMBER(10,2),
    CONSTRAINT FK_CUENTA FOREIGN KEY (CUENTA_ID)
        REFERENCES CUENTA (CUENTA_ID)
        ON DELETE CASCADE
);

-- ==========================================================
-- Fin del script
-- ==========================================================
